### PR TITLE
major refactoring

### PR DESCRIPTION
**Pull request by mehulrastogi**
This PR  is in regards to the 
https://github.com/TomGeorge1234/RatInABox/issues/55

### CODE REVIEW

**Comment by mehulrastogi** [comment]
This needs additional testing to verify the imports

Will also include a `requirements.txt`

**Comment by mehulrastogi** [comment]
Closes #55

**Comment by TomGeorge1234** [comment]
Gonna shelve this for now. It does need to be done but I think it will require a bit of thought from my end (updating all the demos etc.) and I don't have the time rn. It's not exactly going to be backwards compatible so I'm thinking of combining it with a bunch of other updates later down the line, maybe a RiaB2.0.

Happy to reconsider and/or chat once I'm more free in July.

**Comment by mehulrastogi** [comment]
Yes, backward compatibility is an issue with this kind of significant refactoring...i guess its better to have it in a major release but maybe start a branch for it so that the new developments can use the new package structure.

I did solve the imports in the demos but yes more testing is needed

**Comment by TomGeorge1234** [comment]
Ok I made a new branch.

**Comment by TomGeorge1234** [comment]
Ok I merged it into v2_beta branch.

**Pull request merged**
